# Generated by Django 5.2.4 on 2025-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_movimiento_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
