# Generated by Django 5.2.4 on 2025-07-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_movimiento_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
