# Generated by Django 5.2.4 on 2025-07-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_movimiento_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
