# Generated by Django 5.2.4 on 2025-07-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_movimiento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimentación'), ('transporte', 'Transporte'), ('salario', 'Salario'), ('gasolina', 'Gasolina'), ('arriendo', 'Arriendo'), ('servicios', 'Servicios'), ('creditos', 'Creditos'), ('targeta de credito', 'Targeta de credito'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
