# Generated by Django 4.2.23 on 2025-08-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_alter_movimiento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
