# Generated by Django 5.2.4 on 2025-07-30 22:21

import gastos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_alter_movimiento_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimentación'), ('transporte', 'Transporte'), ('salario', 'Salario'), ('gasolina', 'Gasolina'), ('arriendo', 'Arriendo'), ('servicios', 'Servicios'), ('creditos', 'Créditos'), ('targeta_credito', 'Targeta de crédito'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Archivo de comprobante (JPG, PNG, PDF, DOC - máx. 5MB)', null=True, upload_to='comprobantes/', validators=[gastos.models.validar_archivo_comprobante]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del movimiento (máx. 50 caracteres)', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(help_text='Fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto del movimiento (max. 12 dígitos, 2 decimales)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='nota',
            field=models.TextField(blank=True, help_text='Notas adicionales (máx. 150 caracteres)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], help_text='Tipo de movimiento', max_length=10),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['usuario', 'fecha'], name='gastos_movi_usuario_121b26_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['usuario', 'tipo'], name='gastos_movi_usuario_45e993_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['usuario', 'categoria'], name='gastos_movi_usuario_d00598_idx'),
        ),
    ]
