# Generated by Django 4.2.23 on 2025-07-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_alter_movimiento_options_movimiento_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Archivo de comprobante (JPG, PNG, PDF, DOC - máx. 5MB)', null=True, upload_to='comprobantes/'),
        ),
    ]
