# Generated by Django 4.2.23 on 2025-08-06 18:17

from django.db import migrations, models
import gastos.models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0008_alter_movimiento_comprobante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimiento",
            name="comprobante",
            field=models.FileField(
                blank=True,
                help_text="Archivo de comprobante (JPG, PNG, PDF, DOC - máx. 5MB)",
                null=True,
                upload_to="comprobantes/",
                validators=[gastos.models.validar_archivo_comprobante],
            ),
        ),
    ]
