# Generated by Django 4.2.23 on 2025-08-07 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gastos", "0009_alter_movimiento_comprobante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("alimento", "Alimentación"),
                            ("transporte", "Transporte"),
                            ("salario", "Salario"),
                            ("gasolina", "Gasolina"),
                            ("arriendo", "Arriendo"),
                            ("servicios", "Servicios"),
                            ("creditos", "Créditos"),
                            ("targeta_credito", "Targeta de crédito"),
                            ("otros", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "monto_presupuestado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monto_gastado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-año", "-mes", "categoria"],
                "unique_together": {("usuario", "año", "mes", "categoria")},
            },
        ),
    ]
